HTML_FILES= 	editor.html


.PHONY: all
all: ${HTML_FILES}


.PHONY: clean
clean:
	${RM} ${HTML_FILES}


include ../../html.mk

# Canvas items managed from this directory (see ../module.mk)
PAGES+= 	editor.md
include ../module.mk
