SUBDIR+=	overview
SUBDIR+=	ssh
SUBDIR+=	ssh/grading
SUBDIR+=	terminal
SUBDIR+=	terminal/grading
SUBDIR+=	editor
SUBDIR+=	collaboration
SUBDIR+=	git
SUBDIR+=	git/grading
SUBDIR+=	latex
SUBDIR+=	latex/grading

INCLUDE_MAKEFILES=../makefiles
include ${INCLUDE_MAKEFILES}/subdir.mk
